checks:
    php:
        coding_standard:
            name: WordPress
        code_rating: true
        duplication: true
filter:
    dependency_paths:
        - vendor/
        - node_modules/
        - wordpress/
build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
                    - composer require --dev wp-pay/core